[workspace]
members = [
    "async_test",
    "variables",
    "log_test",
    "ropey_test",
    "regex_test",
    "blog",
    "playground",
    "ch03_scrap_url",
    "ch03_grammar",
    "ch10_strtok",
    "httpie",
    "thumbor",
]
