[package]
name = "json_rpc"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
jsonrpc-core = "17.1.0"
jsonrpc-derive = "17.1.0"

